DROP TABLE IF EXISTS CURSO;
CREATE TABLE CURSO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30)

);

INSERT INTO CURSO(NOMBRE) VALUES('Algoritmos');
INSERT INTO CURSO(NOMBRE) VALUES('Ingles');
INSERT INTO CURSO(NOMBRE) VALUES('Php');
INSERT INTO CURSO(NOMBRE) VALUES('Java');
INSERT INTO CURSO(NOMBRE) VALUES('Sql');

DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(30),
APELLIDOS VARCHAR(50),
DNI CHAR(8),
USUARIO VARCHAR(30),
CLAVE VARCHAR(300),
ROLES VARCHAR(50)
);

INSERT INTO USUARIO(NOMBRE,APELLIDOS,DNI,USUARIO,CLAVE,ROLES) VALUES('Francisco','Julca','47467404','admin','dQNjUIMorJb8Ubj2+wVGYp6eAeYkdekqAcnYp+aRq5w=','ROLE_ADMIN');
INSERT INTO USUARIO(NOMBRE,APELLIDOS,DNI,USUARIO,CLAVE,ROLES) VALUES('Jose','Sosa','45464547','jsosa','2222','ROLE_ADMIN');
INSERT INTO USUARIO(NOMBRE,APELLIDOS,DNI,USUARIO,CLAVE,ROLES) VALUES('Andrea','Guzman','34536454','aguzman','3434','ROLE_ADMIN');


DROP TABLE IF EXISTS NOTA;
CREATE TABLE NOTA(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOTA1 NUMERIC,
NOTA2 NUMERIC,
NOTA3 NUMERIC,
NOTA4 NUMERIC,
PROMEDIO DECIMAL,
IDUSUARIO INT,
IDCURSO INT,
foreign key (IDCURSO)
references CURSO (ID),
foreign key (IDUSUARIO)
references USUARIO (ID)
);

INSERT INTO NOTA(NOTA1,NOTA2,NOTA3,NOTA4,PROMEDIO,IDUSUARIO,IDCURSO) VALUES(12,10,15,14,13,1,1);
INSERT INTO NOTA(NOTA1,NOTA2,NOTA3,NOTA4,PROMEDIO,IDUSUARIO,IDCURSO) VALUES(12,15,15,14,14,1,1);
INSERT INTO NOTA(NOTA1,NOTA2,NOTA3,NOTA4,PROMEDIO,IDUSUARIO,IDCURSO) VALUES(12,18,15,14,15,3,1);

